[account_1]
tl_url = "https://demo.tradelocker.com"
tl_email = "you@example.com"
tl_password = "..."
tl_server = "..."
tl_account_id = "..."

[account_2]
tl_url = "https://demo.tradelocker.com"
tl_email = "you@example.com"
tl_password = "..."
tl_server = "..."
tl_account_id = "..."